import logging


def test_log():
    logging.error('this is ERROR')